# Generated by Django 5.2.2 on 2025-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_remove_faq_answer_af_remove_faq_answer_ar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marathon",
            name="public_offer_text",
        ),
        migrations.RemoveField(
            model_name="marathon",
            name="public_offer_text_ru",
        ),
        migrations.RemoveField(
            model_name="marathon",
            name="public_offer_text_uz",
        ),
        migrations.AddField(
            model_name="marathon",
            name="public_offer_link",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marathon",
            name="public_offer_link_ru",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="marathon",
            name="public_offer_link_uz",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
