# Generated by Django 5.2.2 on 2025-06-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_marathon_public_offer_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marathon",
            name="cost",
        ),
        migrations.AddField(
            model_name="marathon",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marathon",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="marathon",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
