# Generated by Django 5.2.2 on 2025-06-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_remove_marathon_cost_marathon_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarathonTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "marathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="bot.marathon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marathon Tarif",
                "verbose_name_plural": "Marathon Tariflar",
            },
        ),
    ]
