# Generated by Django 5.2.2 on 2025-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_marathontarif"),
    ]

    operations = [
        migrations.AddField(
            model_name="marathontarif",
            name="name_ru",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="marathontarif",
            name="name_uz",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
