# Generated by Django 5.2.2 on 2025-06-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_marathontarif_name_ru_marathontarif_name_uz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marathon",
            name="private_channel_link",
        ),
        migrations.AddField(
            model_name="marathontarif",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="marathontarif",
            name="description_ru",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="marathontarif",
            name="description_uz",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="marathontarif",
            name="private_channel_link",
            field=models.CharField(default="", max_length=150),
        ),
    ]
