# Generated by Django 5.2.2 on 2025-06-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_remove_marathon_private_channel_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="chosen_tarif",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="bot.marathontarif",
                verbose_name="Tanlangan Tarif",
            ),
        ),
    ]
