# Generated by Django 5.2.2 on 2025-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_marathontarif_private_group_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marathontarif",
            name="private_group_link",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
